#!/bin/bash

# Start cron (needed for log rotation)
cron -f &

# Set elasticsearch cluster name
cat >> /opt/elasticsearch/config/elasticsearch.yml << EOF
cluster.name: $ES_CLUSTER_NAME
EOF

# Update logstash eleasticsearch config so it uses ec2 discovery
if [ "$ES_DISCOVERY" == "ec2" ] ; then
	cat >> /opt/elasticsearch/config/elasticsearch.yml << EOF
network.publish_host: _ec2_

cloud:
  aws:
    region: $ES_AWS_REGION

discovery:
  type: ec2
  ec2:
    groups: $ES_CLUSTER_NAME
EOF
  if [ "$ES_BUCKET" != "" ] ; then
  	cat >> /opt/elasticsearch/config/elasticsearch.yml << EOF
gateway:
  type: s3
  s3:
    bucket: $ES_BUCKET
EOF
  fi
fi

# Start elasticsearch
/opt/elasticsearch/bin/elasticsearch