#!/bin/bash
# Set elasticsearch cluster name and ip address
cat >> /opt/elasticsearch/config/elasticsearch.yml << EOF
cluster.name: $ES_CLUSTER_NAME
network.host: "_eth0_"
EOF

# Set elasticsearch publish address
if [[ "$ES_PUBLISH_HOST" != "" ]]; then
cat >> /opt/elasticsearch/config/elasticsearch.yml << EOF
network.publish_host: $ES_PUBLISH_HOST
EOF
fi

# Set up unicast discovery
if [[ "$ES_UNICAST_IPS" != "" ]]; then
cat >> /opt/elasticsearch/config/elasticsearch.yml << EOF
discovery.zen.ping.unicast.hosts: [ $ES_UNICAST_IPS ]
EOF
fi

#/usr/bin/supervisord -e trace -c /etc/supervisor/conf.d/elasticsearch.conf
su elasticsearch /opt/elasticsearch/bin/elasticsearch
